### ISSUE TITLE
configuration about ACLRNet-T

### ISSUE THREAD

**Issue by supersonicMaclaurin** [yuweics/ACLRNet#1]
testing param of ACLRNet-T
net = ACLRNet(upscale_factor=4,  ng0=64, ng=24, nbc=2)
But got 1.74M, not same as 1.24M reported in Table2

**Comment by yuweics** [comment]
'nbc' denotes the block's channel, 'nb' denotes  the number of blocks.
ACLRNet-T is net = ACLRNet(upscale_factor=4, ng0=64, ng=24, nbc=4, nb=2).
The parameter size is 1.241M.

**Comment by supersonicMaclaurin** [comment]
Thank you for your prompt response ！
